_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  actions_permissions: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  anonymous_login: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  components: 0
  content_moderation: 0
  contextual: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity: 0
  eva: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flexible_permissions: 0
  fontawesome: 0
  gnode: 0
  group: 0
  group_entity_reference: 0
  group_support_revisions: 0
  group_views_join_link: 0
  groupmedia: 0
  groupmedia_vbo: 0
  help: 0
  image: 0
  inline_form_errors: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  masquerade: 0
  media: 0
  media_entity_download: 0
  media_library: 0
  menu_breadcrumb: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  permissions_dragcheck: 0
  quick_node_clone: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  sdc: 0
  search: 0
  serialization: 0
  settings_tray: 0
  show_email: 0
  smart_date: 0
  smart_date_recur: 0
  subpathauto: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toc_js: 0
  toc_js_per_node: 0
  token: 0
  toolbar: 0
  twbstools: 0
  twig_tweak: 0
  update: 0
  user: 0
  variationcache: 0
  views_bulk_operations: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  pathauto: 1
  views: 10
  publication_date: 99
  minimal: 1000
theme:
  claro: 0
  stable9: 0
  radix: 0
  gin: 0
  xtra: 0
profile: minimal
